name: Whale Runner
on:
  push:
    branches:
      - rsyi/modify-gha
#on:
#  schedule:
#   - cron: "*/5 * * * *"

jobs:
  run-etl:
    runs-on: ubuntu-latest
    steps:

      # Setup python + clone repos
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - uses: actions/checkout@v2
      - name: Copy to ~/.whale
        run: |
          cp -r . ~/.whale
      - uses: actions/checkout@v2
        with:
          repository: dataframehq/whale
          path: whale

      # Scrape from warehouse
      - name: etl
        working-directory: ./whale
        run: |
          echo ${BIGQUERY_JSON} > ~/.whale/credentials.json
          make python
          source ~/.whale/libexec/env/bin/activate
          python ~/.whale/libexec/build_script.py

      # Push to git
      - name: push-to-git
        working-directory: ~/.whale
        run: |
          git config user.name 'GHA Runner'
          git config user.email '<your_username>@users.noreply.github.com'
          git add metadata manifests metrics
          git commit -m "Automated push." || echo "No changes to commit"
          git push
        env:
          BIGQUERY_JSON: ${{ secrets.BIGQUERY_JSON }}
