name: Whale ETL
on:
  schedule:
   - cron: "0 */12 * * *"

jobs:
  run-etl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - uses: actions/checkout@v2
      - name: install
        run: |
          cp -r . ~/.whale/
      - uses: actions/checkout@v2
        with:
          repository: dataframehq/whale
          path: whale
      - name: etl
        working-directory: ./whale
        run: |
          echo ${BIGQUERY_JSON} > ~/.whale/credentials.json
          make python
          mkdir ~/.whale/logs
          source ./build/env/bin/activate
          python ./build/build_script.py
          cd ~/.whale
          git config user.name 'GHA Runner'
          git config user.email '<your_username>@users.noreply.github.com'
          git add metadata manifests metrics
          git commit -m "Automated push." || echo "No changes to commit"
          git push
        env:
          BIGQUERY_JSON: ${{ secrets.BIGQUERY_JSON }}
